system:
  device: auto

databases:
  system: ~/.local/share/omnimanager/system.db
  user:   ~/.local/share/omnimanager/user.db

models:
  - name: instruct
    backend: llama-cpp
    model: models/llama/LiquidAI_LFM2.5-1.2B-Instruct-GGUF_LFM2.5-1.2B-Instruct-Q4_K_M.gguf

  - name: thinking
    backend: llama-cpp
    model: models/llama/LiquidAI_LFM2.5-1.2B-Thinking-GGUF_LFM2.5-1.2B-Thinking-Q4_K_M.gguf
    # parameters:
    #   max_context: 1024

  - name: vision
    backend: vision
    model: models/vision/Janus-Pro-1.3B
    # parameters:
    #   max_context: 1024

  - name: bge-small
    backend: embedding
    model: models/embeddings/bge-small-en-v1.5
    
